version: '3.9'

services:
  bill-app:
    build: .
    environment:
      APP_PORT: ${APP_PORT}
    ports:
      - "${APP_PORT}:5000"
    depends_on:
      bill-db:
        condition: service_healthy

  bill-db:
    image: mysql:5.7
    environment:
      DB_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "billdb"
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ${HOST_VOLUME}:${MYSQL_VOLUME}
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    
networks:
  default:
    name: ${NETWORK}
    external: true

